env: flex
service: default
runtime: go

manual_scaling:
    instances: 1

resources:
    cpu: 2
    memory_gb: 2.0
    disk_size_gb: 10

env_variables:
    GOGC: "500"
    AUTH0_CLIENT_ID: "AKtUIhFrwoEO3fBhFU14a0i957g1f3Xg"
    AUTH0_DOMAIN: "rditech.auth0.com"
    AUTH0_CLIENT_SECRET: "JOSIb83JnIvijs6b9UNY0EwKRDIqVZqJtcAeuFdD6SULMHtGgvS8x5f154jaw3Mn"
    AUTH0_CALLBACK_URL: "https://live.radiationimaging.com/callback"
    AUTH0_LOGOUT_URL: "https://live.radiationimaging.com"
    SESSION_KEY: "kbTmIKuAjfMRSNiYJnBVWZEua763d3KthBf41ynDFRs="
    SECURE_ONLY: "true"
    MAX_NPR: "100"
